services:
  alpen:
    build: .
    container_name: alpen
    networks:
      - default
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data

networks:
  default:
    external: true
    name: newt
