services:
  alpen:
    build: .
    command: >
      dufs /data
      --allow-all
      --enable-cors
      --render-try-index
      --auth admin:admin@/:rw
    container_name: alpen
    image: alpen
    networks:
      - default
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data/storage

networks:
  default:
    external: true
    name: newt
