services:
  alpen:
    build: .
    command: >
      dufs /data
      --allow-all
      --enable-cors
      --render-try-index
      --auth admin:admin@/:rw  # Change this user:pass
    container_name: alpen
    image: alpen
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data/storage
